version: "3.8"

networks:
  test:



services:

  szep-service:
    image: cloud-gateway/szep:latest
    container_name: szep-service
    ports:
      - 9081:9081
    environment:
      - LOKI_URI=http://loki:3100/loki/api/v1/push
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
    networks:
      - test


  api-gateway:
    image: cloud-gateway/api-gateway:latest
    container_name: api-gateway
    depends_on:
      - redis
    #      - keycloak
    ports:
      - 9080:9080
    environment:
      - SZEP_URL=http://szep-service:9081
      - LOKI_URI=http://loki:3100/loki/api/v1/push
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411
      - SPRING_DATA_REDIS_HOST=redis
    #      - KEYCLOAK_URL=http://keycloak:8080
    networks:
      - test

  # Backing Services

  #  keycloak:
  #    image: simaofsilva/keycloak:15.0.2
  #    container_name: keycloak
  #    volumes:
  #      - ./platform/keycloak:/opt/jboss/keycloak/imports
  #    environment:
  #      - KEYCLOAK_USER=admin
  #      - KEYCLOAK_PASSWORD=admin
  #      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
  #    ports:
  #      - 8080:8080
  #    networks:
  #      - test



  # Observability

  grafana:
    image: grafana/grafana:9.3.6
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./platform/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./platform/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - test


  loki:
    image: grafana/loki:2.7.3
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - 3100:3100
    networks:
      - test


  prometheus:
    image: prom/prometheus:v2.42.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - test


  tempo:
    image: grafana/tempo:2.0.0
    container_name: tempo
    command: -config.file /etc/tempo-config.yml
    ports:
      - 3110:3100     # Tempo
      - 4317:4317     # OTel
      - 9411:9411     # Zipkin
    volumes:
      - ./platform/tempo/tempo.yml:/etc/tempo-config.yml
    networks:
      - test


  redis:
    image: redis:7.0.4
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - test